@auth = Basic 2@sirius.com:12345678
###
GET http://localhost:3000/
###
GET http://localhost:3000/recipes
Authorization: {{auth}}
###
POST http://localhost:3000/recipes/new
Authorization: {{auth}}
Content-Type: application/json

{
   "name": "warming ginger tea",
   "category": "beverage",
   "description": "Light, aromatic and refreshing beverage, ...",
   "ingredients": ["boiled water", "honey", "fresh mint leaves"],
   "directions": ["Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"]
}
###
PUT http://localhost:3000/recipes/2
Authorization: {{auth}}
Content-Type: application/json

{
   "name": "Fresh Mint Tea6",
   "description": "Light, aromatic and refreshing beverage, ...",
   "ingredients": ["boiled water", "honey", "fresh mint leaves"],
   "directions": ["Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"],
   "category": "beverage"
}
###
GET http://localhost:3000/recipes/2
Authorization: {{auth}}
###
DELETE http://localhost:3000/recipes/2
Authorization: {{auth}}
###
GET http://localhost:3000/recipes/search?categorsy=bevErage&name=sh
###
GET http://localhost:3000/users
Authorization: {{auth}}
###
POST http://localhost:3000/register
Content-Type: application/json

{
   "email": "1@sirius.com",
   "password": "12345678"
}